version: '3.4'
services:
  jestor-database:
    container_name: jestor-database
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=jestor
      - MYSQL_ROOT_PASSWORD=jestor
    volumes:
      - ../api/dump:/docker-entrypoint-initdb.d
    #  - ./containers/mysql/data/db/mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3306:3306

  jestor-web:
    container_name: jestor-web
    build:
      context: ../
      dockerfile: docker/containers/web/Dockerfile
    restart: always
    environment:
      - PUBLIC_URL=http://localhost:8080/app
    depends_on:
      - jestor-database
    volumes:
      - ../app:/var/www/html/app
      - ../api:/var/www/html/api
    ports:
      - 8080:8080
      - 3000:3000 #dev

networks:
  default:
    external:
      name: jestor-network
